# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme : mmistakes/minimal-mistakes
minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "Klase1337 Blog"
title_separator          : "-"
name                     : "Klase1337"
description              : "CryptoMarket Trends, Mobile Security"
url                      : "https://klase1337.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
